package objects; 

class MainMenuArtsList 
{ 
	public static var data:Map<String,Array<String>> = [ 
		"xeno-slow" => ["too-slow-encore"],
		"xeno-faker" => ["too-slow-encore"],
		"grimbo" => ["too-slow-encore-alt"],
		"xeno-2" => ["you-cant-run"],
		"xeno-encore" => ["you-cant-run-encore"],
		"xeno-3" => ["triple-trouble"],
		"xeno-beast" => ["triple-trouble-encore"],
		"soultails" => ["triple-trouble"],
		"soulknuckles" => ["triple-trouble"],
		"souleggman" => ["triple-trouble"],
		"xeno-4" => ["final-escape"],
		"lookalike" => ["face-off"],
		"gf-alt" => ["goddess"],
		"rosy-alt" => ["coulrophobia"],
		"majin" => ["endless"],
		"majin-encore" => ["endless-encore"],
		"majin-og" => ["endless-og"],
		"majin-jp" => ["endless-jp"],
		"majin-us" => ["endless-us"],
		"buff" => ["endeavors"],
		"lord_x" => ["cycles", "hellbent"],
		"lord_x-encore" => ["cycles-encore"],
		"lord_x-red" => ["gotta-go-red-glove"],
		"sunky-mpeg" => ["milk"],
		"melthog" => ["melting"],
		"melted-bf" => ["confronting"],
		"tailsdoll" => ["sunshine"],
		"tailsdoll-encore" => ["sunshine-encore"],
		"tailsdoll-plushie" => ["soulless"],
		"fleetway" => ["chaos"],
		"fleetway-encore" => ["chaos-encore"],
		"fakerexe" => ["faker"],
		"fakerexe-encore" => ["faker-encore"],
		"fakerexe-real" => ["black-sun"],
		"sanic" => ["too-fest"],
		"christmas" => ["jingle-hells"],
		"fatal-error" => ["fatality"],
		"fatal-encore" => ["fatality-encore"],
		"sonic" => ["prey"],
		"furnace" => ["prey"],
		"starved" => ["fight-or-flight"],
		"needlemouse" => ["relax"],
		"needlemouse-trap" => ["spike-trap"],
		"sarah" => ["round-a-bout"],
		"shadowmouse" => ["round-a-bout-encore"],
		"luther" => ["her-world"],
		"sunter" => ["her-world-encore"],
		"lukas" => ["lukas-world"],
		"coldsteel" => ["personel"],
		"coldsteel-serious" => ["personel-serious"],
		"sh-tails" => ["mania"],
		"demogri" => ["uh-oh"],
		"griatos" => ["marauder"],
		"xterion-1" => ["substantial"],
		"xterion-2" => ["digitalized"],
		"devoid" => ["hollow"],
		"shpsonic" => ["burning"],
		"chaotix" => ["my-horizon"],
		"chaotixreal" => ["our-horizon"],
		"hog" => ["hedge"],
		"scorched" => ["manual-blast"],
		"curse" => ["malediction"],
		"curse-happy" => ["extricate-hex"],
		"normalcd" => ["found-you"],
		"wechidna" => ["my-horizon-wechidna"],
		"wechidnareal" => ["my-horizon-wechidna"],
		"satanos" => ["perdition", "infernal-demise"],
		"educator" => ["expulsion"],
		"noname" => ["forever-unnamed"],
		"gameover" => ["last-hope"],
		"gameover-alt" => ["too-far-alt"],
		"requital" => ["forestall-desire"],
		"sl4sh" => ["b4cksl4sh"],
		"mono" => ["color-blind"],
		"dsk" => ["miasma"],
		"omw" => ["planestrider"],
		"bratwurst" => ["life-and-death"],
		"bratwurst-2" => ["gods-will"],
		"nmi" => ["fake-baby"],
		"grimeware-fake" => ["envy"],
		"exetior" => ["sharpy-showdown"],
		"batman" => ["call-of-justice"],
		"sonichu" => ["shocker", "extreme-zap"],
		"ugly-sonic" => ["ugly"],
		"lemon" => ["soured"],
		"xeno-slaps" => ["old-ycr-slaps"],
		"oxxymajin" => ["oxxynless"]
	]; 
	 
	public static var arts:Array<String> = [
		"xeno-slow",
		"xeno-faker",
		"grimbo",
		"xeno-2",
		"xeno-encore",
		"xeno-3",
		"xeno-beast",
		"soultails",
		"soulknuckles",
		"souleggman",
		"xeno-4",
		"lookalike",
		"gf-alt",
		"rosy-alt",
		"majin",
		"majin-encore",
		"majin-og",
		"majin-jp",
		"majin-us",
		"buff",
		"lord_x",
		"lord_x-encore",
		"lord_x-red",
		"sunky-mpeg",
		"melthog",
		"melted-bf",
		"tailsdoll",
		"tailsdoll-encore",
		"tailsdoll-plushie",
		"fleetway",
		"fleetway-encore",
		"fakerexe",
		"fakerexe-encore",
		"fakerexe-real",
		"sanic",
		"christmas",
		"fatal-error",
		"fatal-encore",
		"sonic",
		"furnace",
		"starved",
		"needlemouse",
		"needlemouse-trap",
		"sarah",
		"shadowmouse",
		"luther",
		"sunter",
		"lukas",
		"coldsteel",
		"coldsteel-serious",
		"sh-tails",
		"demogri",
		"griatos",
		"xterion-1",
		"xterion-2",
		"devoid",
		"shpsonic",
		"chaotix",
		"chaotixreal",
		"chotix",
		"hog",
		"scorched",
		"curse",
		"curse-happy",
		"normalcd",
		"wechidna",
		"wechidnareal",
		"satanos",
		"educator",
		"noname",
		"gameover",
		"gameover-alt",
		"requital",
		"sl4sh",
		"mono",
		"dsk",
		"omw",
		"bratwurst",
		"bratwurst-2",
		"nmi",
		"grimeware-fake",
		"exetior",
		"batman",
		"sonichu",
		"ugly-sonic",
		"lemon",
		"xeno-slaps",
		"oxxymajin"
	]; 
	
	public static var secretArts:Array<String> = [
		"2011",
		"alpha",
		"baby-x",
		"bufcoo",
		"camiloaf",
		"catherious",
		"cherry",
		"chikal",
		"chotix",
		"coolcat",
		"crimson",
		"cursed-beast",
		"demonix",
		"doobus",
		"enanismo",
		"erect",
		"estaguy",
		"exieco",
		"faceling",
		"fanon",
		"feet",
		"first-apparition",
		"forgotten",
		"gangsta",
		"gay",
		"grimbooba",
		"harigami",
		"harigami-final",
		"hedgehog",
		"imperial",
		"inski",
		"kawaii",
		"ladytails",
		"lego",
		"litr",
		"liz",
		"loaf",
		"lois",
		"luc",
		"mandibulin",
		"maniax",
		"minus",
		"mokey",
		"mrgenesis",
		"overdrive",
		"palsonic",
		"pendrive",
		"phantomarcade",
		"plushie",
		"raton-aguja",
		"raw",
		"saldavid",
		"sans",
		"santiago",
		"silly-billy",
		"sketch-hog",
		"slander",
		"snick",
		"soink",
		"sonk",
		"sonykos",
		"soonc",
		"soulamy-soulshadow",
		"squidwurst",
		"sunky",
		"sunky-mamado",
		"symbiote-speed",
		"tanic",
		"theory",
		"walter",
		"woman",
		"xendio"
	];
	
	public static var songToArt:Map<String,String>=[]; 
	
	public static function init() {
		songToArt.clear(); 
		for(character in data.keys()) { 
			var songs = data.get(character); 
			for(song in songs)songToArt.set(song,character); 
		}
	} 
	
     public static function getSongsByArt(char:String) { 
		if(data.exists(char))return data.get(char);
		return []; 
	} 
}