haxelib set actuate 1.9.0
haxelib set box2d 1.2.3
haxelib git android-ndk https://github.com/android/ndk
haxelib install away3d 5.0.9
haxelib install extension-android-support-v4 1.0.0
haxelib install extension-androidtools 1.8.0
haxelib git extension-webm https://github.com/HaxeExtension/extension-webm
haxelib git faxe https://github.com/ashea-code/faxe
haxelib set discord_rpc git
haxelib set flixel 4.9.0
haxelib set flixel-addons 2.10.0
haxelib set flixel-tools 1.5.1
haxelib set flixel-ui 2.3.3
haxelib set hscript 2.4.0
haxelib set hxCodec 3.0.2
haxelib set openfl 9.1.0
haxelib remove hxcpp
haxelib set hxcpp 4.2.1
haxelib set lime 7.9.0
haxelib set sscript 8.1.6
haxelib set lime-samples 7.0.0
